 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/get-dgg-stats-staging:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/get-dgg-stats-staging:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'beta'
   - 'run'
   - 'jobs'
   - 'update'
   - 'get-dgg-stats-staging'
   - '--image'
   - 'gcr.io/$PROJECT_ID/get-dgg-stats-staging:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--set-env-vars'
   - 'DGG_STATS_DB=dgg_stats_staging.db'

 images:
 - 'gcr.io/$PROJECT_ID/get-dgg-stats-staging:$COMMIT_SHA'